#!/bin/bash

echo "FYBORG3000 (c) FNNDSC, BCH 2013"

if [ -z "$3" ]
then
  echo "USAGE: `basename $0` {FREESURFER_DIR} {DIFFUSION_DICOM_DIR} {OUTPUT_DIR} {DECIMATION} {RADIUS} [-v]"
  exit 1
fi

FREESURFER_DIR=$1
DIFFUSION_DICOM_DIR=$2
OUTPUT_DIR=$3
SUPER_DECIMATION_LEVEL=$4
SUPER_RADIUS=$5

#
# PREPARATION (ONLY NEEDS TO BE RUN ONCE)
#
#./fy0.bash $FREESURFER_DIR $DIFFUSION_DICOM_DIR $OUTPUT_DIR -v

#
# SIMPLE SURFACE MAPPING (NO RADIUS)
#
#
#DECIMATION_LEVEL=0.1
#./fy1.bash $FREESURFER_DIR $DIFFUSION_DICOM_DIR $OUTPUT_DIR $DECIMATION_LEVEL -v

#
# ADVANCED SURFACE MAPPING (RADIUS)
#

printf "Using decimation %s and radius %s\n" $SUPER_DECIMATION_LEVEL $SUPER_RADIUS
S_OUTPUT_DIR=$OUTPUT_DIR/$SUPER_DECIMATION_LEVEL-$SUPER_RADIUS
printf "Using final directory %s\n" $S_OUTPUT_DIR
./fy2.bash $FREESURFER_DIR $DIFFUSION_DICOM_DIR $OUTPUT_DIR $S_OUTPUT_DIR $SUPER_DECIMATION_LEVEL $SUPER_RADIUS -v

echo 'All done.'
